### ISSUE TITLE
为什么要用hard/absolute link呢？ 

### ISSUE THREAD

**Issue by jianpingbadao** [openset/leetcode#745]
想问一下，为什么solution的link、题目分组的link，要指向remote呢？这样的话，其他人fork之后，点击solution，会跳转到网页。直接指向本地repo里面的file，会不会更好一些？

**Comment by openset** [comment]
你说的很好，这样做的目的一部分原因就是为了导流到本项目。我是希望大家共同参与起来维护一个项目，共同学习交流，而不是每人维护一个项目。另外本项目会及时更新，其他fork后的项目很少再更新，本项目会更新所有题目相关信息，包含必须订阅的题目描述，相似问题，描述修改，问题分类都是和官网同步，fork后的项目很难做到。

**Comment by openset** [comment]
Solution链接不能用相对路径。原因如下：例如这几个链接[https://github.com/openset/leetcode](https://github.com/openset/leetcode)，[https://github.com/openset/leetcode/](https://github.com/openset/leetcode/)
，[https://github.com/openset/leetcode/tree/master](https://github.com/openset/leetcode/tree/master)指向的都是同一个readme，如果用相对路径，打开的文件会是404。
